### ISSUE TITLE
Unclear directions

### ISSUE THREAD

**Issue by kcamloyd** [learn-co-curriculum/js-if-else-files-lab#13]
For the lesson "Practicing Conditional Statements" -
<img width="901" alt="screen shot 2017-10-12 at 9 58 29 am" src="https://user-images.githubusercontent.com/32081347/31499887-02ff1346-af34-11e7-8bdf-ac166172b389.png">
In order to get the correct output in the terminal, the index.js file must be saved.
In the next section, "Separating tests from application code," the intended output ("Give that a run by typing nodejs other_file.js and you should see the name getting printed out.") assumes the original file is being run, not the saved version. The saved version with the if/else statement outputs:
The name is correct
Susan

The final exercise, "Your turn," also assumes the index.js file has been returned to the original state.

The readme should clarify when to save/revert to the original index.js document, unless you meant to create a problem just to see if students can figure it out. If so, well done. As you were.

**Comment by sgharms** [comment]
Resolved by #18
