### ISSUE TITLE
confusing wording 

### ISSUE THREAD

**Issue by cmansetmitchell** [learn-co-curriculum/js-if-else-files-lab#17]
at the end of the lesson we are told to modify index.js so that --- 

"when you run tests.js it says you got both height and name"

this is a confusing statement. what does "got" mean? got what? the contents of the height and name variable? just them? or also the prompt that says our input is correct? hopelessly unclear. please reword to be clearer about what you're asking for.

**Comment by sgharms** [comment]
Resolved by #18
