### ISSUE TITLE
height number in tests.js is not in quotations

### ISSUE THREAD

**Issue by aebenw** [learn-co-curriculum/js-if-else-files-lab#22]
not sure if intended but the test for height does not have quotations around it leading to an error. this could be a test of attention to detail, but just wanted to raise the issue if its an error.

**Comment by Donnadieu** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration
in upcoming releases of this curriculum. 

As always, thanks for contributing! 💙
