### ISSUE TITLE
There is no Open IDE button: change lab directions

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/js-if-else-files-lab#23]
The directions say: _After you open this lesson in the IDE, double-click on index.js. You'll see some basic code:_

Make it clear that students need to manually fork and clone from github to see the files referred to.

**Comment by mobesa** [comment]
![Screenshot](https://cdn.pbrd.co/images/HoCuxdL.png)

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
