### ISSUE TITLE
No IDE button to open the IDE (instead, "SANDBOX")

### ISSUE THREAD

**Issue by brschneider** [learn-co-curriculum/js-if-else-files-lab#26]
Even though the lesson states "After you open this lesson in the IDE...", there isn't actually an IDE button on this page. Only a SANDBOX button which doesn't contain the files and text the lesson mentions.

**Comment by emauldin84** [comment]
Experiencing the same issue with lesson: "Practicing Conditional Statements"

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
