### ISSUE TITLE
Not showing "Open IDE" 

### ISSUE THREAD

**Issue by orlandowatson1** [learn-co-curriculum/js-if-else-files-lab#27]
Hi - This part of the curriculum is not showing an "Open IDE" for me to practice conditional statements. I only see a button for Sandbox. Is there another way to complete this lesson's task?

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
