### ISSUE TITLE
Not seeing IDE...Missing Files

### ISSUE THREAD

**Issue by emauldin84** [learn-co-curriculum/js-if-else-files-lab#28]
Wondering where the rest of the IDE files are...All I can see in the Sandbox is READEME.md. The way the narrative reads, I should have the option for the IDE and see an assortment of files. Please advise.

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
