### ISSUE TITLE
Misleading directions since this lab doesn't have an open IDE option

### ISSUE THREAD

**Issue by hansenjl** [learn-co-curriculum/js-if-else-files-lab#29]
The readme states: "After you open this lesson in the IDE, double-click on index.js. You'll see some basic code:" 

However, this lab only has the option of opening the Sandbox. Many students ask about this and are confused because of this. I would suggest either switching it back to a lab with the IDE or providing clear instructions about how to clone the lab into the sandbox. 

@DanielSeehausen

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
