### ISSUE TITLE
No IDE

### ISSUE THREAD

**Issue by Mmcray** [learn-co-curriculum/js-if-else-files-lab#30]
Is this lesson supposed to have an IDE, because all I am getting is the Sandbox.

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
