### ISSUE TITLE
There is no IDE in this lesson available to open

### ISSUE THREAD

**Issue by BadAssDeadpool276** [learn-co-curriculum/js-if-else-files-lab#32]
There is no IDE in this lesson available to open, instead sandbox appears to have replaced it as the option for using the developer tool. And, it is impossible to change directory from sandbox to js-if-else-files-lab-bootcamp-prep-000/index.js because they are not in the same file tree. Since the IDE is required to fully comprehend this lesson, it would be great if this could be fixed as soon as possible. If I am misunderstanding how this lab is supposed to work, please notify me so as to correct user error.

Sincerly,
Wyatt Massey

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
