### ISSUE TITLE
Sandbox not IDE appears on button in this lab/lesson

### ISSUE THREAD

**Issue by pmknyc** [learn-co-curriculum/js-if-else-files-lab#33]
In the Practicing Conditional Statements lesson in Bootcamp prep. the lesson text says to use the IDE but the button to open the IDE is linked to the Sandbox instead (see attached PNG file). I had installed the Learn IDE 3 per instructions. Rebooted computer. Still got the Sandbox button. I'm using Windows 7 OS, and Chrome browser. In other lessons I correctly see the IDE button for labs where we're supposed to use it.

I did a workaround by forking & cloning the lab from Github, but wonder if there's a tech issue with this lesson?  Just wanted to let you know! Thanks!

![lesson_conditionals_sandbox-error](https://user-images.githubusercontent.com/39341352/41741393-f25164c6-7568-11e8-88fb-9e8e88201f51.PNG)

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
