### ISSUE TITLE
Open IDE

### ISSUE THREAD

**Issue by tristangerardbrown** [learn-co-curriculum/js-if-else-files-lab#34]
There is no button to open the IDE in the lesson "practice conditional statements." the Sandbox just has a readme file

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
