### ISSUE TITLE
Had to manually grab files from github

### ISSUE THREAD

**Issue by algakovic** [learn-co-curriculum/js-if-else-files-lab#35]
During this lesson, the open IDE button was not present only "open sandbox".
I was able to complete the lesson via creating my own files in the sandbox and copy pasting code from github manually.

**Comment by morwen80** [comment]
This is ridiculous and frankly it's discouraging seeing that learning platform has that kind of oversights and, more importantly, nobody answered all of our questions. 
May I ask where, exactly, did you find the missing code? I'm stuck at the "Your Turn" bit, when they ask to open tests.js which, of course, is missing too.

**Comment by algakovic** [comment]
Thankfully , I had my partner who is ahead on the track and in the full
program to help me out.

We went to github by pressing the cat icon and then clicked fork. "Already
forked " may pop up that's fine and then you just go to your files or
theirs and find the file name your looking for and copy the contents.

That's what we did . Please feel free to follow up with me if you still run
in to trouble, it's not straightforward.

Best wishes.
Alek

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
