### ISSUE TITLE
no tests.js

### ISSUE THREAD

**Issue by imanj12** [learn-co-curriculum/js-if-else-files-lab#37]
Upon opening the in-browser IDE (technically Sandbox), the file directory was empty. Was able to create a few js files to start the lab, however without tests.js, was not able to complete the lab.

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
