### ISSUE TITLE
OPEN IDE FILES

### ISSUE THREAD

**Issue by omo2nde** [learn-co-curriculum/js-if-else-files-lab#41]
NO EXISTING FILE APPEARED ON MY JS

**Comment by sheriefCloud** [comment]
THe Conditional Statements Practice opened with no files 
![image](https://user-images.githubusercontent.com/29527317/52150291-5946c880-2624-11e9-9d1c-a180c5b2eabb.png)

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
