### ISSUE TITLE
IDE Opened with no files

### ISSUE THREAD

**Issue by sheriefCloud** [learn-co-curriculum/js-if-else-files-lab#43]
My Conditional Statements Practice IDE has no files 
![image](https://user-images.githubusercontent.com/29527317/52150322-7380a680-2624-11e9-963d-82c0b2817fb8.png)

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
