### ISSUE TITLE
Your Turn

### ISSUE THREAD

**Issue by courtneymorgan** [learn-co-curriculum/js-if-else-files-lab#5]
In the last section of the lesson, it asks you to modify index.js so when you run test.js it shows you have both height and name. If the results are supposed to reflect the bottom image, is the expectation to replace "Susan" with "Joe" in index.js?

Previously, we found the error in the lesson text where it said "Joe" when it should have said "Susan" so just trying to make sure that this was the direction and not a typo.
![screen shot 2017-06-29 at 4 29 03 pm](https://user-images.githubusercontent.com/29407254/27709057-c80719a2-5ce8-11e7-9284-25a0df0708c0.png)

**Comment by jmburges** [comment]
Fixed with commit 90e8bd6492ce50f58bfaee69af78606601065857

Thanks!
