### ISSUE TITLE
Load Issue

### ISSUE THREAD

**Issue by cav3man420** [learn-co-curriculum/js-if-else-files-lab#50]
No matter what I try to do I continue to try and open the IDE project and it fails every time. It fails to open the project each time I try. How can I continue if the program doesnt work.

**Comment by Donnadieu** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
