### ISSUE TITLE
Asking a Question

### ISSUE THREAD

**Issue by katrinamariegist** [learn-co-curriculum/js-if-else-files-lab#7]
Im trying to ask a question about running my code in the terminal and it wont give me the option to ask the question.

**Comment by gj** [comment]
Hi there,

There's a great article about this very issue over in the [Learn Help Center](http://help.learn.co/). Check it out! 🎉

http://help.learn.co/instructional-support/receiving-course-support/ask-a-question-isnt-working

Thanks! 💙
